### ISSUE TITLE
ESP8266 version

### ISSUE THREAD

**Issue by jaroslavas** [skorokithakis/tiny-ESP8266-breakout#1]
Nice work!
I think You should state clearly in the readme which version of ESP8266 has to be used, as there are many of them available: http://www.esp8266.com/wiki/doku.php?id=esp8266-module-family

**Comment by mcauser** [comment]
- ESP-07
- ESP-12
- ESP-12E
- ESP-12Q
- ESP-12F
- ESP-14

**Comment by skorokithakis** [comment]
Ah, you're right, and @mcauser has the list. I'll add it, thank you both!
